# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.run-api-tests.outputs.test }}
    environment: 	testenv
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run postman tests
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
          echo "env var ${{ vars.URLGOOGLE }}"
          echo ${{ secrets.URL }}
          echo "done"
      - name: Run API tests
        id: run-api-tests
        run: |
          postman collection run "${{ github.workspace }}/Postman Collections/postmancollection.json"
      - name: Print Step Outcome
        run: |
          if [ ${{ steps.run-api-tests.outcome }} == 'success' ]; then
            echo "API tests were successful"
          else
            echo "API tests failed"
          fi

          # Set the output based on the success/failure
          if [ ${{ steps.run-api-tests.outcome }} == 'success' ]; then
            echo "test=success" >> "$GITHUB_OUTPUT"
          else
            echo "test=failed" >> "$GITHUB_OUTPUT"
          fi
