name: My starter workflow

on:
  workflow_dispatch:

jobs:
  call-workflow-in-local-repo:
    uses: ./.github/workflows/blank.yml
  second-job:
    needs: call-workflow-in-local-repo
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Sample Step
        run: |
          echo ${{ needs.call-workflow-in-local-repo.outputs.firstword }} ${{ needs.call-workflow-in-local-repo.outputs.secondword }}
