name: My starter workflow

on:
  workflow_dispatch:

jobs:
  call-workflow-in-local-repo:
    uses: ./.github/workflows/blank.yml
  second-job:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Sample Step
        run: |
          echo result: call-workflow-in-local-repo.result
