name: My starter workflow

on:
  workflow_dispatch:

jobs:
  job1:
    uses: ./.github/workflows/blank.yml
  second-job:
    needs: job1
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Sample Step
        run: |
          echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
