name: Postman test 1

on:
  workflow_dispatch:
    inputs:
      environment_name:
        type: choice
        description: 'environment'
        options:
        - Test
        - Staging
        - Production
        default: Test
      tests_to_run:
        type: choice
        description: 'Tests to run'
        options:
        - BuildingRead
        - ParcelRead
        default: Test
  workflow_call:
    inputs:
      environment_name:
        type: string
      tests_to_run:
        type: string
    outputs:
      status:
        description: "The status of the tests"
        value: ${{ jobs.tests.outputs.output1 }}
env:
  Test: "test is chosen"
  Staging: "staging is chosen"

jobs:
  # This workflow contains a single job called "build"
  tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.fill-in-state.outputs.status }}
    environment: 	testenv
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run postman tests
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
          echo "env var ${{ vars.URLGOOGLE }}"
          echo ${{ secrets.URL }}
          echo "done"
      - name: Run API tests
        id: run-api-tests
        run: |
          postman collection run "${{ github.workspace }}/Postman Collections/postmancollection.json"
      - id: fill-in-state
        run:  
          echo ${{ github.event.inputs.tests_to_run }}
          echo ${{ env[inputs.environment_name] }}
          echo "status=${{steps.run-api-tests.outcome}}" >> $GITHUB_OUTPUT
