name: Reusable workflow 1

on: 
  workflow_call:

jobs:
  ru1-job:
    runs-on: ubuntu-latests
    
    steps:
     - uses: actions/checkout@v3
     - name: write something to log
       run: |
        echo "I am reusable workflow one"
