name: slack notify

on:
  workflow_dispatch:

jobs:
  register1:
    uses: ./.github/workflows/postmantest1.yml
    with:
      environment_name: Staging
      tests_to_run: Address
  second-job:
    needs: register1
    if: always()
    name: notify-slack
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variable Based on Condition
        run: |
          if ${{ (needs.register1.outputs.status == 'success') && (needs.register1.outputs.status == 'success') }} ; then
            echo "Setting MY_VARIABLE to 'success'"
            echo "ALL_TESTS_SUCCEEDED=success" >> $GITHUB_ENV
          else
            echo "Setting MY_VARIABLE to 'failure'"
            echo "ALL_TESTS_SUCCEEDED=failure" >> $GITHUB_ENV
          fi
      - name: Send to slack
        if: always()
        uses: bryannice/gitactions-slack-notification@2.0.0
        env:
          SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }} # required
          SLACK_MESSAGE: |
            register1 = ${{ needs.register1.outputs.status }}
            register2 = ${{ needs.register1.outputs.status }}
            register3 = ${{ needs.register1.outputs.status }}
          SLACK_TITLE: '{workflow} has {status_message}'
          SLACK_CHANNEL: general
      - name: print
        run: echo ${{ needs.register1.outputs.status }} $ALL_TESTS_SUCCEEDED ${{ vars.ALL_TESTS_SUCCEEDED }}
