name: slack notify

on:
  workflow_dispatch:

jobs:
  register1:
    uses: ./.github/workflows/postmantest1.yml
  second-job:
    needs: register1
    name: notify-slack
    runs-on: ubuntu-latest
    steps:
      - name: Send to slack
        uses: ravsamhq/notify-slack-action@v2
        if: always()
        with:
          status: ${{ job.status }} # required
          notification_title: '{workflow} has {status_message}'
          message_format: register1 = ${{ needs.register1.outputs.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
