name: Trigger Workflows

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - workflow_dispatch

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow CI
        uses: actions/workflow-dispatch@v2
        with:
          workflow: "CI"
          ref: main  # The branch you want to trigger Workflow A on
