name: Run After All Workflows

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run your desired action
      run: |
        # Add your custom code or command here
        echo "All workflows are completed. Running this action now."
        gh run blank.yml
