name: Trigger Workflows

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow CI
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          workflow: CI
